Variables:
  Hubspot:
    # Either use an api Key for direct backend login (End user must not login)
    # Or clientId and clientSecret for OAuth2 (End user must login in the browser)
    Auth:
      #[password]
      apikey:
      clientId:
      #[password]
      clientSecret:
